CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE sets (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ownerId INT NOT NULL,
   name VARCHAR(255) NOT NULL,
   FOREIGN KEY (ownerId) REFERENCES users(id)
);

CREATE TABLE cards (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   setId INT NOT NULL,
   frontText VARCHAR(255),
   backText MEDIUMTEXT,
   FOREIGN KEY (setId) REFERENCES sets(id)
);